### ISSUE TITLE
Use standard library lxml.etree instead libmei for exporting MEI files

### ISSUE THREAD

**Issue by tiagovaz** [belangeo/qlive#4]
After some tests I think we'll be better served using lxml.etree rather than an external library to generate the MEI xml files. Also, libmei doesn't seem up to date with last MEI schema and we don't want to maintain another piece of software for QLive needs.

I'll update this issue as soon as I do a cleanup in the code and restart the MEI classes using lxml.etree.

**Comment by belangeo** [comment]
Maybe I missed something, but why not using [xml.etree.ElementTree](https://docs.python.org/2/library/xml.etree.elementtree.html#module-xml.etree.ElementTree) ? It's part of the standard python distribution...

**Comment by tiagovaz** [comment]
You're right, I meant xml.etree, not lxml!

**Comment by belangeo** [comment]
It's funny, lxml.etree exists! 

[http://lxml.de/api.html](http://lxml.de/api.html)

**Comment by tiagovaz** [comment]
Just started using xml.etree and removed libmei, so closing this issue.
