### ISSUE TITLE
Add new top menu "Edit" for general preferences

### ISSUE THREAD

**Issue by tiagovaz** [belangeo/qlive#5]
The menu "File" should provide options related to the current Qlive project. I think we should provide another top menu for general setup/edition.

A very standard way to achieve this is providing a top "Edit" menu, which may also contain options as _Undo, Redo, Cut, Copy, Paste_ etc... I like the way Audacity software presents it.

Once agreed I can make it quickly, as I'm already coding the "project meta-data" input interface.

**Comment by belangeo** [comment]
It's ok with me! We just need to make it clear that cut/copy/paste only involve cues! Undo/Redo are not implemented yet...
